### ISSUE TITLE
Code refactoring and unit tests

### ISSUE THREAD

**Issue by breucode** [FAForever/Neroxis-Map-Generator#27]
I noticed, that there are currently no unit tests in this project and only static methods are used.

If you want, I can refactor the code (mainly using dependency injection and cluster the logic into smaller classes) to make it easily testable and then write unit tests for the parts of the application, which I am able to understand (I am not familiar with FAForever :D).

We can of course have discussions, how we approach that.

**Comment by Geosearchef** [comment]
This project implements a map generator that isn't very demaning software engineering wise. That's why it's using static code, there's no need or gain from using object orientation.

Another issue is it being focused on run time, which would probably be hurt from employing techniques like dependency injection.

I also don't see a reason to unit test, what do you wanna test? This is not a complex application, it's a simple map generator that has code for generation and import/export.

In case of this project, I'd say KISS.

**Comment by Geosearchef** [comment]
I've also seen you've been doing some pull requests on FAF repos, are you in any way related to FAF or hunting hacktoberfest PRs :) ?

**Comment by breucode** [comment]
> This project implements a map generator that isn't very demaning software engineering wise. That's why it's using static code, there's no need or gain from using object orientation.
> 
> Another issue is it being focused on run time, which would probably be hurt from employing techniques like dependency injection.
> 
> I also don't see a reason to unit test, what do you wanna test? This is not a complex application, it's a simple map generator that has code for generation and import/export.
> 
> In case of this project, I'd say KISS.

Fair enough, I will close this issue then.
